name: Release

on:
  workflow_dispatch:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      
permissions:
  actions: write
  contents: write

jobs:
  release:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    environment: deploy-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: ./node_modules/.bin/sls package
    - uses: actions/upload-artifact@v3
      with:
        name: zip-s3-lambda.zip
        path: .serverless/serverless-zip-s3.zip
